// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMqRV65JdvZasWcGrRGux0ePCO6Aj20xs',
    appId: '1:318787225771:web:1c72a50789a6598e20cfee',
    messagingSenderId: '318787225771',
    projectId: 'news-app-a038e',
    authDomain: 'news-app-a038e.firebaseapp.com',
    storageBucket: 'news-app-a038e.appspot.com',
    measurementId: 'G-17YWT2BY74',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVUg3LCxXXYVxtO8Fa5E21n-AEeHhD6I0',
    appId: '1:318787225771:android:418a63d35880791c20cfee',
    messagingSenderId: '318787225771',
    projectId: 'news-app-a038e',
    storageBucket: 'news-app-a038e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqv4xjxHOF0d2THyK9yZFqCDPSwQ8LXS4',
    appId: '1:318787225771:ios:6b0dd6eed20ce2e420cfee',
    messagingSenderId: '318787225771',
    projectId: 'news-app-a038e',
    storageBucket: 'news-app-a038e.appspot.com',
    iosBundleId: 'com.superiordev.demo.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqv4xjxHOF0d2THyK9yZFqCDPSwQ8LXS4',
    appId: '1:318787225771:ios:6b0dd6eed20ce2e420cfee',
    messagingSenderId: '318787225771',
    projectId: 'news-app-a038e',
    storageBucket: 'news-app-a038e.appspot.com',
    iosBundleId: 'com.superiordev.demo.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMqRV65JdvZasWcGrRGux0ePCO6Aj20xs',
    appId: '1:318787225771:web:15f8029cce793e5a20cfee',
    messagingSenderId: '318787225771',
    projectId: 'news-app-a038e',
    authDomain: 'news-app-a038e.firebaseapp.com',
    storageBucket: 'news-app-a038e.appspot.com',
    measurementId: 'G-PWXET9DD2X',
  );
}
